name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - name: Debug File System
      run: |
        echo "Listing root directory:"
        ls -la
        echo "Listing speiseplan_projekt directory:"
        ls -la ./speiseplan_projekt

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./speiseplan_projekt

    - name: Build
      run: npm run build --if-present
      working-directory: ./speiseplan_projekt

    - name: Run Tests
      run: npm test
      working-directory: ./speiseplan_projekt
