name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - name: Print Working Directory
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files in the current directory:"
        ls -la

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      working-directory: ./speiseplan_projekt
      run: npm ci

    - name: Build
      working-directory: ./speiseplan_projekt
      run: npm run build --if-present

    - name: Run Tests
      working-directory: ./speiseplan_projekt
      run: npm test

